from BaseApp import BaseApp
import tkinter as tk
from tkinter import ttk, messagebox  # Para estilos e caixas de diálogo


# Dados dos métodos 
methods_data = {
    "MNDO": [
      {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
        {"symbol": "Li", "name": "Lithium", "atomic_number": 3},
        {"symbol": "Be", "name": "Beryllium", "atomic_number": 4},
        {"symbol": "B", "name": "Boron", "atomic_number": 5},
        {"symbol": "C", "name": "Carbon", "atomic_number": 6},
        {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
        {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
        {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
        {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
        {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
        {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
        {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
        {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
        {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
        {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
        {"symbol": "K", "name": "Potassium", "atomic_number": 19},
        {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
        {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
        {"symbol": "Ga", "name": "Gallium", "atomic_number": 31},
        {"symbol": "Ge", "name": "Germanium", "atomic_number": 32},
        {"symbol": "As", "name": "Arsenic", "atomic_number": 33},
        {"symbol": "Se", "name": "Selenium", "atomic_number": 34},
        {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
        {"symbol": "Rb", "name": "Rubidium", "atomic_number": 37},
        {"symbol": "Sr", "name": "Strontium", "atomic_number": 38},
        {"symbol": "In", "name": "Indium", "atomic_number": 49},
        {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
        {"symbol": "Sb", "name": "Antimony", "atomic_number": 51},
        {"symbol": "Te", "name": "Tellurium", "atomic_number": 52},
        {"symbol": "I", "name": "Iodine", "atomic_number": 53},
        {"symbol": "Cs", "name": "Cesium", "atomic_number": 55},
        {"symbol": "Ba", "name": "Barium", "atomic_number": 56},
        {"symbol": "Hg", "name": "Mercury", "atomic_number": 80},
        {"symbol": "Tl", "name": "Thallium", "atomic_number": 81},
        {"symbol": "Pb", "name": "Lead", "atomic_number": 82},
        {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83}
    ],
    "AM1": [
        {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
        {"symbol": "Li", "name": "Lithium", "atomic_number": 3},
        {"symbol": "Be", "name": "Beryllium", "atomic_number": 4},
        {"symbol": "B", "name": "Boron", "atomic_number": 5},
        {"symbol": "C", "name": "Carbon", "atomic_number": 6},
        {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
        {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
        {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
        {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
        {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
        {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
        {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
        {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
        {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
        {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
        {"symbol": "K", "name": "Potassium", "atomic_number": 19},
        {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
        {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
        {"symbol": "Ga", "name": "Gallium", "atomic_number": 31},
        {"symbol": "Ge", "name": "Germanium", "atomic_number": 32},
        {"symbol": "As", "name": "Arsenic", "atomic_number": 33},
        {"symbol": "Se", "name": "Selenium", "atomic_number": 34},
        {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
        {"symbol": "Rb", "name": "Rubidium", "atomic_number": 37},
        {"symbol": "Sr", "name": "Strontium", "atomic_number": 38},
        {"symbol": "In", "name": "Indium", "atomic_number": 49},
        {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
        {"symbol": "Sb", "name": "Antimony", "atomic_number": 51},
        {"symbol": "Te", "name": "Tellurium", "atomic_number": 52},
        {"symbol": "I", "name": "Iodine", "atomic_number": 53},
        {"symbol": "Cs", "name": "Cesium", "atomic_number": 55},
        {"symbol": "Ba", "name": "Barium", "atomic_number": 56},
        {"symbol": "Hg", "name": "Mercury", "atomic_number": 80},
        {"symbol": "Tl", "name": "Thallium", "atomic_number": 81},
        {"symbol": "Pb", "name": "Lead", "atomic_number": 82},
        {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83},
        {"symbol": "La", "name": "Lanthanum", "atomic_number": 138.91},
        {"symbol": "Ce", "name": "Cerium", "atomic_number": 140.12},
        {"symbol": "Pr", "name": "Praseodímio", "atomic_number": 140.91},
        {"symbol": "Nd", "name": "Neodymium", "atomic_number": 144.24},
        {"symbol": "Pm", "name": "Promethium", "atomic_number": 145},
        {"symbol": "Sm", "name": "Samaria", "atomic_number": 150.36},
        {"symbol": "Eu", "name": "Europe", "atomic_number": 151.96},
        {"symbol": "Gd", "name": "Gadolinium", "atomic_number": 157.25},
        {"symbol": "Tb", "name": "Terbio", "atomic_number": 158.93},
        {"symbol": "Dy", "name": "Dysprosium", "atomic_number": 165.5},
        {"symbol": "Ho", "name": "Holmio", "atomic_number": 164.93},
        {"symbol": "Er", "name": "Érbio", "atomic_number": 167.26},
        {"symbol": "Tm", "name": "Thulium", "atomic_number": 168.93},
        {"symbol": "Yb", "name": "Turbid", "atomic_number": 173.04},
        {"symbol": "Lu", "name": "Lutetium", "atomic_number": 174.97}
    ],
    "PM3": [
        {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
        {"symbol": "Li", "name": "Lithium", "atomic_number": 3},
        {"symbol": "Be", "name": "Beryllium", "atomic_number": 4},
        {"symbol": "B", "name": "Boron", "atomic_number": 5},
        {"symbol": "C", "name": "Carbon", "atomic_number": 6},
        {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
        {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
        {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
        {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
        {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
        {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
        {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
        {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
        {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
        {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
        {"symbol": "K", "name": "Potassium", "atomic_number": 19},
        {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
        {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
        {"symbol": "Ga", "name": "Gallium", "atomic_number": 31},
        {"symbol": "Ge", "name": "Germanium", "atomic_number": 32},
        {"symbol": "As", "name": "Arsenic", "atomic_number": 33},
        {"symbol": "Se", "name": "Selenium", "atomic_number": 34},
        {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
        {"symbol": "Rb", "name": "Rubidium", "atomic_number": 37},
        {"symbol": "Sr", "name": "Strontium", "atomic_number": 38},
        {"symbol": "Y", "name": "Yttrium", "atomic_number": 39},
        {"symbol": "Zr", "name": "Zirconium", "atomic_number": 40},
        {"symbol": "Mo", "name": "Molybdenum", "atomic_number": 42},
        {"symbol": "Pd", "name": "Palladium", "atomic_number": 46},
        {"symbol": "In", "name": "Indium", "atomic_number": 49},
        {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
        {"symbol": "Sb", "name": "Antimony", "atomic_number": 51},
        {"symbol": "Te", "name": "Tellurium", "atomic_number": 52},
        {"symbol": "I", "name": "Iodine", "atomic_number": 53},
        {"symbol": "Cs", "name": "Cesium", "atomic_number": 55},
        {"symbol": "Ba", "name": "Barium", "atomic_number": 56},
        {"symbol": "Hg", "name": "Mercury", "atomic_number": 80},
        {"symbol": "Tl", "name": "Thallium", "atomic_number": 81},
        {"symbol": "Pb", "name": "Lead", "atomic_number": 82},
        {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83},
        {"symbol": "La", "name": "Lanthanum", "atomic_number": 138.91},
        {"symbol": "Ce", "name": "Cerium", "atomic_number": 140.12},
        {"symbol": "Pr", "name": "Praseodímio", "atomic_number": 140.91},
        {"symbol": "Nd", "name": "Neodymium", "atomic_number": 144.24},
        {"symbol": "Pm", "name": "Promethium", "atomic_number": 145},
        {"symbol": "Sm", "name": "Samaria", "atomic_number": 150.36},
        {"symbol": "Eu", "name": "Europe", "atomic_number": 151.96},
        {"symbol": "Gd", "name": "Gadolinium", "atomic_number": 157.25},
        {"symbol": "Tb", "name": "Terbio", "atomic_number": 158.93},
        {"symbol": "Dy", "name": "Dysprosium", "atomic_number": 165.5},
        {"symbol": "Ho", "name": "Holmio", "atomic_number": 164.93},
        {"symbol": "Er", "name": "Érbio", "atomic_number": 167.26},
        {"symbol": "Tm", "name": "Thulium", "atomic_number": 168.93},
        {"symbol": "Yb", "name": "Turbid", "atomic_number": 173.04},
        {"symbol": "Lu", "name": "Lutetium", "atomic_number": 174.97}
        
    ],
    "RM1": [
        {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
        {"symbol": "C", "name": "Carbon", "atomic_number": 6},
        {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
        {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
        {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
        {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
        {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
        {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
        {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
        {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
        {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
        {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
        {"symbol": "K", "name": "Potassium", "atomic_number": 19},
        {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
        {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
        {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
        {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
        {"symbol": "I", "name": "Iodine", "atomic_number": 53},
        {"symbol": "La", "name": "Lanthanum", "atomic_number": 138.91},
        {"symbol": "Ce", "name": "Cerium", "atomic_number": 140.12},
        {"symbol": "Pr", "name": "Praseodímio", "atomic_number": 140.91},
        {"symbol": "Nd", "name": "Neodymium", "atomic_number": 144.24},
        {"symbol": "Pm", "name": "Promethium", "atomic_number": 145},
        {"symbol": "Sm", "name": "Samaria", "atomic_number": 150.36},
        {"symbol": "Eu", "name": "Europe", "atomic_number": 151.96},
        {"symbol": "Gd", "name": "Gadolinium", "atomic_number": 157.25},
        {"symbol": "Tb", "name": "Terbio", "atomic_number": 158.93},
        {"symbol": "Dy", "name": "Dysprosium", "atomic_number": 165.5},
        {"symbol": "Ho", "name": "Holmio", "atomic_number": 164.93},
        {"symbol": "Er", "name": "Érbio", "atomic_number": 167.26},
        {"symbol": "Tm", "name": "Thulium", "atomic_number": 168.93},
        {"symbol": "Yb", "name": "Turbid", "atomic_number": 173.04},
        {"symbol": "Lu", "name": "Lutetium", "atomic_number": 174.97}
    ],
    "PM6": [
        {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
       {"symbol": "Li", "name": "Lithium", "atomic_number": 3},
       {"symbol": "Be", "name": "Beryllium", "atomic_number": 4},
       {"symbol": "B", "name": "Boron", "atomic_number": 5},
       {"symbol": "C", "name": "Carbon", "atomic_number": 6},
       {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
       {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
       {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
       {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
       {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
       {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
       {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
       {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
       {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
       {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
       {"symbol": "K", "name": "Potassium", "atomic_number": 19},
       {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
       {"symbol": "Sc", "name": "Scandium", "atomic_number": 21},
       {"symbol": "Ti", "name": "Titanium", "atomic_number": 22},
       {"symbol": "V", "name": "Vanadium", "atomic_number": 23},
       {"symbol": "Cr", "name": "Chromium", "atomic_number": 24},
       {"symbol": "Mn", "name": "Manganese", "atomic_number": 25},
       {"symbol": "Fe", "name": "Iron", "atomic_number": 26},
       {"symbol": "Co", "name": "Cobalt", "atomic_number": 27},
       {"symbol": "Ni", "name": "Nickel", "atomic_number": 28},
       {"symbol": "Cu", "name": "Copper", "atomic_number": 29},
       {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
       {"symbol": "Ga", "name": "Gallium", "atomic_number": 31},
       {"symbol": "Ge", "name": "Germanium", "atomic_number": 32},
       {"symbol": "As", "name": "Arsenic", "atomic_number": 33},
       {"symbol": "Se", "name": "Selenium", "atomic_number": 34},
       {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
       {"symbol": "Zr", "name": "Zirconium", "atomic_number": 40},
       {"symbol": "Nb", "name": "Niobium", "atomic_number": 41},
       {"symbol": "Mo", "name": "Molybdenum", "atomic_number": 42},
       {"symbol": "Ru", "name": "Ruthenium", "atomic_number": 44},
       {"symbol": "Rh", "name": "Rhodium", "atomic_number": 45},
       {"symbol": "Pd", "name": "Palladium", "atomic_number": 46},
       {"symbol": "Ag", "name": "Silver", "atomic_number": 47},
       {"symbol": "Cd", "name": "Cadmium", "atomic_number": 48},
       {"symbol": "In", "name": "Indium", "atomic_number": 49},
       {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
       {"symbol": "Sb", "name": "Antimony", "atomic_number": 51},
       {"symbol": "Te", "name": "Tellurium", "atomic_number": 52},
       {"symbol": "I", "name": "Iodine", "atomic_number": 53},
       {"symbol": "Hf", "name": "Hafnium", "atomic_number": 72},
       {"symbol": "Ta", "name": "Tantalum", "atomic_number": 73},
       {"symbol": "W", "name": "Tungsten", "atomic_number": 74},
       {"symbol": "Re", "name": "Rhenium", "atomic_number": 75},
       {"symbol": "Os", "name": "Osmium", "atomic_number": 76},
       {"symbol": "Ir", "name": "Iridium", "atomic_number": 77},
       {"symbol": "Pt", "name": "Platinum", "atomic_number": 78},
       {"symbol": "Au", "name": "Gold", "atomic_number": 79},
       {"symbol": "Hg", "name": "Mercury", "atomic_number": 80},
       {"symbol": "Pb", "name": "Lead", "atomic_number": 82},
       {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83}
    ],
    "PM7": [
        {"symbol": "H", "name": "Hydrogen", "atomic_number": 1},
        {"symbol": "Li", "name": "Lithium", "atomic_number": 3},
        {"symbol": "Be", "name": "Beryllium", "atomic_number": 4},
        {"symbol": "B", "name": "Boron", "atomic_number": 5},
        {"symbol": "C", "name": "Carbon", "atomic_number": 6},
        {"symbol": "N", "name": "Nitrogen", "atomic_number": 7},
        {"symbol": "O", "name": "Oxygen", "atomic_number": 8},
        {"symbol": "F", "name": "Fluorine", "atomic_number": 9},
        {"symbol": "Na", "name": "Sodium", "atomic_number": 11},
        {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12},
        {"symbol": "Al", "name": "Aluminum", "atomic_number": 13},
        {"symbol": "Si", "name": "Silicon", "atomic_number": 14},
        {"symbol": "P", "name": "Phosphorus", "atomic_number": 15},
        {"symbol": "S", "name": "Sulfur", "atomic_number": 16},
        {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17},
        {"symbol": "K", "name": "Potassium", "atomic_number": 19},
        {"symbol": "Ca", "name": "Calcium", "atomic_number": 20},
        {"symbol": "Sc", "name": "Scandium", "atomic_number": 21},
        {"symbol": "Ti", "name": "Titanium", "atomic_number": 22},
        {"symbol": "V", "name": "Vanadium", "atomic_number": 23},
        {"symbol": "Cr", "name": "Chromium", "atomic_number": 24},
        {"symbol": "Mn", "name": "Manganese", "atomic_number": 25},
        {"symbol": "Fe", "name": "Iron", "atomic_number": 26},
        {"symbol": "Co", "name": "Cobalt", "atomic_number": 27},
        {"symbol": "Ni", "name": "Nickel", "atomic_number": 28},
        {"symbol": "Cu", "name": "Copper", "atomic_number": 29},
        {"symbol": "Zn", "name": "Zinc", "atomic_number": 30},
        {"symbol": "Ga", "name": "Gallium", "atomic_number": 31},
        {"symbol": "Ge", "name": "Germanium", "atomic_number": 32},
        {"symbol": "As", "name": "Arsenic", "atomic_number": 33},
        {"symbol": "Se", "name": "Selenium", "atomic_number": 34},
        {"symbol": "Br", "name": "Bromine", "atomic_number": 35},
        {"symbol": "Y", "name": "Yttrium", "atomic_number": 39},
        {"symbol": "Zr", "name": "Zirconium", "atomic_number": 40},
        {"symbol": "Nb", "name": "Niobium", "atomic_number": 41},
        {"symbol": "Mo", "name": "Molybdenum", "atomic_number": 42},
        {"symbol": "Ru", "name": "Ruthenium", "atomic_number": 44},
        {"symbol": "Rh", "name": "Rhodium", "atomic_number": 45},
        {"symbol": "Pd", "name": "Palladium", "atomic_number": 46},
        {"symbol": "Ag", "name": "Silver", "atomic_number": 47},
        {"symbol": "Cd", "name": "Cadmium", "atomic_number": 48},
        {"symbol": "In", "name": "Indium", "atomic_number": 49},
        {"symbol": "Sn", "name": "Tin", "atomic_number": 50},
        {"symbol": "Sb", "name": "Antimony", "atomic_number": 51},
        {"symbol": "Te", "name": "Tellurium", "atomic_number": 52},
        {"symbol": "I", "name": "Iodine", "atomic_number": 53},
        {"symbol": "Hf", "name": "Hafnium", "atomic_number": 72},
        {"symbol": "Ta", "name": "Tantalum", "atomic_number": 73},
        {"symbol": "W", "name": "Tungsten", "atomic_number": 74},
        {"symbol": "Re", "name": "Rhenium", "atomic_number": 75},
        {"symbol": "Os", "name": "Osmium", "atomic_number": 76},
        {"symbol": "Ir", "name": "Iridium", "atomic_number": 77},
        {"symbol": "Pt", "name": "Platinum", "atomic_number": 78},
        {"symbol": "Au", "name": "Gold", "atomic_number": 79},
        {"symbol": "Hg", "name": "Mercury", "atomic_number": 80},
        {"symbol": "Tl", "name": "Thallium", "atomic_number": 81},
        {"symbol": "Pb", "name": "Lead", "atomic_number": 82},
        {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83}
    ]
}



# Lista completa de elementos da tabela periódica com sua posição
elements = [
    {"symbol": "H", "row": 0, "col": 0, "color": "#ffcccc"},
    {"symbol": "He", "row": 0, "col": 17, "color": "#ffcccc"},
    {"symbol": "Li", "row": 1, "col": 0, "color": "#ffcc99"},
    {"symbol": "Be", "row": 1, "col": 1, "color": "#ffcc99"},
    {"symbol": "B", "row": 1, "col": 12, "color": "#ccccff"},
    {"symbol": "C", "row": 1, "col": 13, "color": "#ccccff"},
    {"symbol": "N", "row": 1, "col": 14, "color": "#ccccff"},
    {"symbol": "O", "row": 1, "col": 15, "color": "#ccccff"},
    {"symbol": "F", "row": 1, "col": 16, "color": "#ccccff"},
    {"symbol": "Ne", "row": 1, "col": 17, "color": "#ffcccc"},
    {"symbol": "Na", "row": 2, "col": 0, "color": "#ffcc99"},
    {"symbol": "Mg", "row": 2, "col": 1, "color": "#ffcc99"},
    {"symbol": "Al", "row": 2, "col": 12, "color": "#cccc99"},
    {"symbol": "Si", "row": 2, "col": 13, "color": "#cccc99"},
    {"symbol": "P", "row": 2, "col": 14, "color": "#cccc99"},
    {"symbol": "S", "row": 2, "col": 15, "color": "#cccc99"},
    {"symbol": "Cl", "row": 2, "col": 16, "color": "#cccc99"},
    {"symbol": "Ar", "row": 2, "col": 17, "color": "#ffcccc"},
    {"symbol": "K", "row": 3, "col": 0, "color": "#ffcc99"},
    {"symbol": "Ca", "row": 3, "col": 1, "color": "#ffcc99"},
    {"symbol": "Sc", "row": 3, "col": 2, "color": "#ccccff"},
    {"symbol": "Ti", "row": 3, "col": 3, "color": "#ccccff"},
    {"symbol": "V", "row": 3, "col": 4, "color": "#ccccff"},
    {"symbol": "Cr", "row": 3, "col": 5, "color": "#ccccff"},
    {"symbol": "Mn", "row": 3, "col": 6, "color": "#ccccff"},
    {"symbol": "Fe", "row": 3, "col": 7, "color": "#ccccff"},
    {"symbol": "Co", "row": 3, "col": 8, "color": "#ccccff"},
    {"symbol": "Ni", "row": 3, "col": 9, "color": "#ccccff"},
    {"symbol": "Cu", "row": 3, "col": 10, "color": "#ccccff"},
    {"symbol": "Zn", "row": 3, "col": 11, "color": "#ccccff"},
    {"symbol": "Ga", "row": 3, "col": 12, "color": "#cccc99"},
    {"symbol": "Ge", "row": 3, "col": 13, "color": "#cccc99"},
    {"symbol": "As", "row": 3, "col": 14, "color": "#cccc99"},
    {"symbol": "Se", "row": 3, "col": 15, "color": "#cccc99"},
    {"symbol": "Br", "row": 3, "col": 16, "color": "#cccc99"},
    {"symbol": "Kr", "row": 3, "col": 17, "color": "#ffcccc"},
    {"symbol": "Rb", "row": 4, "col": 0, "color": "#ffcc99"},
    {"symbol": "Sr", "row": 4, "col": 1, "color": "#ffcc99"},
    {"symbol": "Y", "row": 4, "col": 2, "color": "#ccccff"},
    {"symbol": "Zr", "row": 4, "col": 3, "color": "#ccccff"},
    {"symbol": "Nb", "row": 4, "col": 4, "color": "#ccccff"},
    {"symbol": "Mo", "row": 4, "col": 5, "color": "#ccccff"},
    {"symbol": "Tc", "row": 4, "col": 6, "color": "#ccccff"},
    {"symbol": "Ru", "row": 4, "col": 7, "color": "#ccccff"},
    {"symbol": "Rh", "row": 4, "col": 8, "color": "#ccccff"},
    {"symbol": "Pd", "row": 4, "col": 9, "color": "#ccccff"},
    {"symbol": "Ag", "row": 4, "col": 10, "color": "#ccccff"},
    {"symbol": "Cd", "row": 4, "col": 11, "color": "#ccccff"},
    {"symbol": "In", "row": 4, "col": 12, "color": "#cccc99"},
    {"symbol": "Sn", "row": 4, "col": 13, "color": "#cccc99"},
    {"symbol": "Sb", "row": 4, "col": 14, "color": "#cccc99"},
    {"symbol": "Te", "row": 4, "col": 15, "color": "#cccc99"},
    {"symbol": "I", "row": 4, "col": 16, "color": "#cccc99"},
    {"symbol": "Xe", "row": 4, "col": 17, "color": "#ffcccc"},
    {"symbol": "Cs", "row": 5, "col": 0, "color": "#ffcc99"},
    {"symbol": "Ba", "row": 5, "col": 1, "color": "#ffcc99"},
    {"symbol": "La", "row": 6, "col": 2, "color": "#ffcc66"},
    {"symbol": "Ce", "row": 6, "col": 3, "color": "#ffcc66"},
    {"symbol": "Pr", "row": 6, "col": 4, "color": "#ffcc66"},
    {"symbol": "Nd", "row": 6, "col": 5, "color": "#ffcc66"},
    {"symbol": "Pm", "row": 6, "col": 6, "color": "#ffcc66"},
    {"symbol": "Sm", "row": 6, "col": 7, "color": "#ffcc66"},
    {"symbol": "Eu", "row": 6, "col": 8, "color": "#ffcc66"},
    {"symbol": "Gd", "row": 6, "col": 9, "color": "#ffcc66"},
    {"symbol": "Tb", "row": 6, "col": 10, "color": "#ffcc66"},
    {"symbol": "Dy", "row": 6, "col": 11, "color": "#ffcc66"},
    {"symbol": "Ho", "row": 6, "col": 12, "color": "#ffcc66"},
    {"symbol": "Er", "row": 6, "col": 13, "color": "#ffcc66"},
    {"symbol": "Tm", "row": 6, "col": 14, "color": "#ffcc66"},
    {"symbol": "Yb", "row": 6, "col": 15, "color": "#ffcc66"},
    {"symbol": "Lu", "row": 6, "col": 16, "color": "#ffcc66"},
    {"symbol": "Hf", "row": 5, "col": 3, "color": "#ccccff"},
    {"symbol": "Ta", "row": 5, "col": 4, "color": "#ccccff"},
    {"symbol": "W", "row": 5, "col": 5, "color": "#ccccff"},
    {"symbol": "Re", "row": 5, "col": 6, "color": "#ccccff"},
    {"symbol": "Os", "row": 5, "col": 7, "color": "#ccccff"},
    {"symbol": "Ir", "row": 5, "col": 8, "color": "#ccccff"},
    {"symbol": "Pt", "row": 5, "col": 9, "color": "#ccccff"},
    {"symbol": "Au", "row": 5, "col": 10, "color": "#ccccff"},
    {"symbol": "Hg", "row": 5, "col": 11, "color": "#ccccff"},
    {"symbol": "Tl", "row": 5, "col": 12, "color": "#cccc99"},
    {"symbol": "Pb", "row": 5, "col": 13, "color": "#cccc99"},
    {"symbol": "Bi", "row": 5, "col": 14, "color": "#cccc99"},
    {"symbol": "Po", "row": 5, "col": 15, "color": "#cccc99"},
    {"symbol": "At", "row": 5, "col": 16, "color": "#cccc99"},
    {"symbol": "Rn", "row": 5, "col": 17, "color": "#ffcccc"},
    {"symbol": "Fr", "row": 6, "col": 0, "color": "#ffcc99"},
    {"symbol": "Ra", "row": 6, "col": 1, "color": "#ffcc99"},
    {"symbol": "Ac", "row": 7, "col": 2, "color": "#ffcc66"},
    {"symbol": "Th", "row": 7, "col": 3, "color": "#ffcc66"},
    {"symbol": "Pa", "row": 7, "col": 4, "color": "#ffcc66"},
    {"symbol": "U", "row": 7, "col": 5, "color": "#ffcc66"},
    {"symbol": "Np", "row": 7, "col": 6, "color": "#ffcc66"},
    {"symbol": "Pu", "row": 7, "col": 7, "color": "#ffcc66"},
    {"symbol": "Am", "row": 7, "col": 8, "color": "#ffcc66"},
    {"symbol": "Cm", "row": 7, "col": 9, "color": "#ffcc66"},
]

class ElementosApp(BaseApp):
    """Classe para exibir a tabela periódica e mostrar os métodos dos elementos"""
    def __init__(self):
        super().__init__("Tabela Periódica", "1000x600")
        #self.iconbitmap("software_assistant_icon.ico") 
        self.frame = tk.Frame(self)
        self.frame.pack()

        self.output_label = tk.Label(self, text="Clique em um elemento para ver os métodos.",
                                     justify=tk.LEFT, padx=10, pady=10, bg="#ffffff")
        self.output_label.pack(fill=tk.BOTH, expand=True)

        self.create_buttons()

    def create_buttons(self):
        """Cria os botões da tabela periódica"""
        for element in elements:
            self.create_periodic_button(element)

    def create_periodic_button(self, element):
        """Cria um botão para cada elemento"""
        btn = tk.Button(self.frame, text=element["symbol"], width=5, height=2, bg=element["color"],
                        command=lambda e=element["symbol"]: self.show_element_info(e))
        btn.grid(row=element["row"], column=element["col"], padx=5, pady=5)

    def show_element_info(self, symbol):
        """Exibe os métodos onde o elemento está presente com mais detalhes"""
        methods = [
            method for method, elems in methods_data.items() 
            if any(e["symbol"] == symbol for e in elems)
        ]

        if methods:
            method_info = []
            for method in methods:
                elements_in_method = [e for e in methods_data[method] if e["symbol"] == symbol]
                for element in elements_in_method:
                    element_details = f"{element['symbol']} ({element['name']}, Atômico: {element['atomic_number']})"
                    method_info.append(f"{method}: {element_details}")
            self.output_label.config(text="\n".join(method_info))
        else:
            self.output_label.config(text=f"{symbol} não pertence a nenhum método.")

if __name__ == "__main__":
    ElementosApp.iconbitmap("software_assistant_icon.ico")
    ElementosApp().mainloop()